blog/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (
    PostListView, PostDetailView, PostCategoryView, PostArchiveIndexView, PostYearArchiveView, PostMonthArchiveView,
    PostDayArchiveView,
    TaggingCloudView, TaggingPostListView, LatestPostFeed
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url='/blog/posts'), name='blog-index'),

    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),
    url(r'^posts/$',
        PostListView.as_view(), name='post-list'),

    url(r'^category/(?P<slug>[-\w]+)/$',
        PostCategoryView.as_view(), name='post-category'),

    url(r'^archive/$',
        PostArchiveIndexView.as_view(), name='post-archive'),
    url(r'^archive/(?P<year>\d{4})/$',
        PostYearArchiveView.as_view(), name='post-year-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        PostMonthArchiveView.as_view(month_format='%m'), name='post-month-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        PostDayArchiveView.as_view(month_format='%m'), name='post-day-archive'),

    url(r'^tags/$',
        TaggingCloudView.as_view(), name='tagging-cloud'),
    url(r'^tags/(?P<tag>[^/]+(?u))/$',
        TaggingPostListView.as_view(), name='tagging-post-list'),

    url(r'^feed/$',
        LatestPostFeed(), name='post-feed'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from account.views import UserLoginView

urlpatterns = [
    # Index page
    url(r'^$',
        RedirectView.as_view(url='/page/index'), name='index'),

    # Project own apps
    url(r'^blog/',
        include('blog.urls', namespace='blog')),
    url(r'^board/',
        include('board.urls', namespace='board')),
    url(r'^page/',
        include('page.urls', namespace='page')),
    url(r'^accounts/',
        include('account.urls', namespace='account')),

    url(r'^comments/',
        include('django_comments_xtd.urls')),

    # Admin site
    # Redirect default admin login page into custom login page
    url(r'admin/login/',
        UserLoginView.as_view()),
    url(r'^admin/',
        admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from easy_thumbnails.fields import ThumbnailerImageField
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from tagging.fields import TagField

from model_utils.models import TimeStampedModel
from .managers import PostManager


class Post(TimeStampedModel):
    DRAFT = 0
    PUBLISHED = 1

    STATUS_CHOICES = (
        (DRAFT, _('Draft')),
        (PUBLISHED, _('Published')),
    )

    title = models.CharField(
        verbose_name=_('Title'),
        help_text=_('Enter blog post title.'),
        max_length=250
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        help_text=_('Enter blog post slug.'),
        max_length=250,
        unique=False,
        allow_unicode=True
    )
    category = TreeForeignKey(
        'Category',
        verbose_name=_('Category'),
        help_text=_('Enter blog post category.'),
        null=True,
        blank=True,
        db_index=True
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Author'),
        help_text=_('Specify blog post author.'),
        related_name='blog_posts'
    )
    description = models.TextField(
        verbose_name=_('Description'),
        help_text=_("Enter blog post description which doesn't contain HTML tags"),
        blank=True
    )
    content = models.TextField(
        verbose_name=_('Content'),
        help_text = _('Enter blog post content.'),
    )
    date_published = models.DateTimeField(
        verbose_name=_('Date published'),
        help_text=_('Enter blog post published date.'),
        null=True
    )
    view_count = models.PositiveIntegerField(
        verbose_name=_('View Count'),
        default=0
    )
    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP Address')
    )
    status = models.IntegerField(
        verbose_name=_('Status'),
        help_text=_('Specify blog post status.'),
        choices=STATUS_CHOICES,
        default=DRAFT
    )
    allow_comments = models.BooleanField(
        verbose_name=_('Allow comments'),
        default=True
    )
    tag = TagField(
        verbose_name=_('Tag')
    )
    thumbnail = ThumbnailerImageField(
        verbose_name=_('Thumbnail'),
        upload_to='blog/thumbnails/%Y/%m',
        blank=True
    )

    objects = PostManager()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ('-date_published',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', args=(self.pk, self.slug,))

    def get_previous_post(self):
        previous_post = Post.objects.published() \
            .filter(id__lt=self.id) \
            .order_by('-date_published').first()

        if previous_post is None:
            return None

        return reverse('blog:post-detail', args=(previous_post.pk, previous_post.slug,))

    def get_next_post(self):
        next_post = Post.objects.published() \
            .filter(id__gt=self.id) \
            .order_by('-date_published').last()

        if next_post is None:
            return None

        return reverse('blog:post-detail', args=(next_post.pk, next_post.slug,))


class Image(TimeStampedModel):
    post = models.ForeignKey(
        Post,
        verbose_name=_('Post'),
        related_name='blog_posts'
    )
    image = models.ImageField(
        verbose_name=_('Image'),
        upload_to='blog/images/%Y/%m'
    )

    class Meta:
        verbose_name = _('image')
        verbose_name_plural = _('images')
        ordering = ['created']

    def __str__(self):
        return self.image.name


class Category(TimeStampedModel, MPTTModel):
    parent = TreeForeignKey(
        'self',
        verbose_name=_('Parent'),
        blank=True,
        null=True,
        related_name='children',
        db_index=True
    )
    title = models.CharField(
        verbose_name=_('Title'),
        max_length=128
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=250,
        unique=True,
        allow_unicode=True
    )
    position = models.IntegerField(
        verbose_name=_('Position'),
        default=1,
    )

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')
        ordering = ['tree_id', 'lft']

    class MPTTMeta:
        order_insertion_by = ['position']

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from rabiang_editor.widgets import SimpleMDEWidget

from .models import Post


class PostSearchForm(forms.Form):
    q = forms.CharField(
        label=_('Search Word'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Search Word'),
                'required': 'True',
            }
        )
    )


class PostAdminForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = []
        options = getattr(settings, "SIMPLEMDE_OPTIONS", '')
        widgets = {
            'content': SimpleMDEWidget(wrapper_class='simplemde-box-admin', options=options),
        }

blog/views.py
import logging

from django.conf import settings
from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    ListView, DetailView, TemplateView
)
from django.views.generic.dates import (
    ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView
)
from tagging.views import TaggedObjectList

from .models import (
    Post, Category
)
from .viewmixins import (
    PageableMixin, SearchContextMixin, CategoryContextMixin
)


class PostListView(PageableMixin, SearchContextMixin, CategoryContextMixin, ListView):
    logger = logging.getLogger(__name__)
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        self.logger.debug('PostListView.get_queryset()')
        form = self.form_class(self.request.GET)
        queryset = Post.objects.published().select_related('author').select_related('category')

        if form.is_valid():
            q = form.cleaned_data['q']
            queryset = queryset.filter(
                Q(title__icontains=q) |
                Q(description__icontains=q) |
                Q(content__icontains=q)
            )

        return queryset.order_by('-date_published')

    def get_context_data(self, **kwargs):
        self.logger.debug('PostListView.get_context_data()')
        context = super(PostListView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostDetailView(SearchContextMixin, CategoryContextMixin, DetailView):
    logger = logging.getLogger(__name__)
    queryset = Post.objects.published().select_related('author').select_related('category')
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'

    def get_object(self, queryset=None):
        self.logger.debug('PostDetailView.get_object()')
        object = super(PostDetailView, self).get_object()
        object.view_count += 1
        object.save()
        return object

    def get_context_data(self, **kwargs):
        self.logger.debug('PostDetailView.get_context_data()')
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostCategoryView(PageableMixin, SearchContextMixin, CategoryContextMixin, ListView):
    logger = logging.getLogger(__name__)
    context_object_name = 'posts'
    template_name = 'blog/post_category_list.html'

    def get_queryset(self):
        self.logger.debug('PostCategoryView.get_queryset()')
        queryset = Post.objects.published().select_related('author').select_related('category') \
            .filter(category__in=Category.objects.filter(slug=self.kwargs['slug']).get_descendants(include_self=True))
        return queryset.order_by('-date_published')

    def get_context_data(self, **kwargs):
        self.logger.debug('PostCategoryView.get_context_data()')
        context = super(PostCategoryView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostArchiveIndexView(PageableMixin, SearchContextMixin, CategoryContextMixin, ArchiveIndexView):
    queryset = Post.objects.published().order_by('-date_published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive.html'
    date_field = 'date_published'

    def get_context_data(self, **kwargs):
        self.logger.debug('PostArchiveIndexView.get_context_data()')
        context = super(PostArchiveIndexView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostYearArchiveView(PageableMixin, SearchContextMixin, CategoryContextMixin, YearArchiveView):
    queryset = Post.objects.published().order_by('-date_published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_year.html'
    date_field = 'date_published'
    make_object_list = True

    def get_context_data(self, **kwargs):
        self.logger.debug('PostYearArchiveView.get_context_data()')
        context = super(PostYearArchiveView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostMonthArchiveView(PageableMixin, SearchContextMixin, CategoryContextMixin, MonthArchiveView):
    queryset = Post.objects.published().order_by('-date_published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_month.html'
    date_field = 'date_published'

    def get_context_data(self, **kwargs):
        self.logger.debug('PostMonthArchiveView.get_context_data()')
        context = super(PostMonthArchiveView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class PostDayArchiveView(PageableMixin, SearchContextMixin, CategoryContextMixin, DayArchiveView):
    queryset = Post.objects.published().order_by('-date_published')
    context_object_name = 'posts'
    template_name = 'blog/post_archive_day.html'
    date_field = 'date_published'

    def get_context_data(self, **kwargs):
        self.logger.debug('PostDayArchiveView.get_context_data()')
        context = super(PostDayArchiveView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class TaggingCloudView(SearchContextMixin, CategoryContextMixin, TemplateView):
    template_name = 'blog/tagging_cloud.html'

    def get_context_data(self, **kwargs):
        self.logger.debug('TaggingCloudView.get_context_data()')
        context = super(TaggingCloudView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class TaggingPostListView(PageableMixin, SearchContextMixin, CategoryContextMixin, TaggedObjectList):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/tagging_post_list.html'

    def get_context_data(self, **kwargs):
        self.logger.debug('TaggingPostListView.get_context_data()')
        context = super(TaggingPostListView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class LatestPostFeed(Feed):
    title = _('Blog Feeds')
    link = '/feed'
    description = _('Blog Recent Posts')

    def items(self):
        return Post.objects.published().order_by('-date_published')[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        return reverse('blog:post-detail', args=(item.pk, item.slug,))

templates/blog/blog_base.html
{% extends "base.html" %}

{% load i18n %}
{% load cache %}
{% load comments_xtd %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- breadcrumb -->
            {% load navbar_tags %}
            {% navbar_breadcrumbs %}

            {% block entry %}{% endblock %}

            {% cache 0 blog_sidebar %}
                <!-- Blog Sidebar Widgets Column -->
                <div class="col-md-4">

                    <!-- Blog Search Well -->
                    <div class="well">
                        <h4>{% trans 'Blog Search' %}</h4>
                        <form action="{% url 'blog:post-list' %}" method="get" class="input-group">
                            {{ form.q }}
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                        </span>
                        </form>
                    </div>

                    <!-- Side Widget Well -->
                    <div class="well">
                        <h4>Side Widget Well</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
                            accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                    </div>

                    <!-- Blog Categories Well -->
                    <div class="well">
                        <h4>{% trans 'Blog Categories' %}</h4>
                        <div class="row">
                            <div class="col-lg-12">
                                <ul>
                                    {% load mptt_tags %}
                                    {% recursetree category_tree %}
                                        {% if not node.is_leaf_node %}
                                            <li>
                                                <a href="{% url 'blog:post-category' node.slug %}">{% trans node.title %}</a>
                                                <ul>
                                                    {{ children }}
                                                </ul>
                                            </li>
                                        {% else %}
                                            <li>
                                                <a href="{% url 'blog:post-category' node.slug %}">{% trans node.title %}</a>
                                            </li>
                                        {% endif %}
                                    {% endrecursetree %}
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="well">
                        <h4>{% trans 'Popular Tags' %}</h4>
                        <div>
                            {% load tagging_tags %}
                            {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
                            {% for tag in tags %}
                                <a href="{% url 'blog:tagging-post-list' tag.name %}"
                                   class="label label-default">{{ tag.name }}</a>&nbsp;
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Recent Posts Well -->
                    <div class="well">
                        <h4>{% trans 'Recent Posts' %}</h4>
                        {% load blog_tags %}
                        <ul>
                            {% get_recent_posts 5 as posts %}
                            {% for post in posts %}
                                <li><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:25 }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- Recent Comments Well -->
                    <div class="well">
                        <h4>{% trans 'Recent Comments' %}</h4>
                        <ul class="media-list">
                            {% render_last_xtdcomments 5 for blog.post %}
                        </ul>
                        <!-- Disqus Comments tag
                        load disqus_tags
                        disqus_recent_comments
                        -->
                    </div>

                    <!-- Meta -->
                    <div class="well">
                        <h4>{% trans 'Meta' %}</h4>
                        <ul>
                            <li><a href="{% url 'blog:post-archive' %}">{% trans 'Blog Archive' %}</a></li>
                            <li><a href="{% url 'blog:tagging-cloud' %}">{% trans 'Tag Cloud' %}</a></li>
                            <li><a href="{% url 'blog:post-feed' %}">{% trans 'RSS' %}</a></li>
                            {% if user.is_superuser %}
                                <li><a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            {% endcache %}
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

templates/blog/post_archive.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Blog Archive' %} : {{ site_title }}{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>
            {% trans 'Blog Archive' %}
        </h2>

        <ul>
            {% for date in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post-year-archive' date|date:'Y' %}">
                        {% blocktrans with year=date|date:'Y' %}Year - {{ year }}{% endblocktrans %}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.date_published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <hr/>
        {% include 'blog/_pagination.html' with page_obj=page_obj page_range=page_range %}
    </div>
{% endblock %}

templates/blog/post_archive_month.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% blocktrans with m=month|date:_('N, Y') %}Monthly archive {{ m }}{% endblocktrans %} : {{ site_title }}{% endblock %}

{% block entry %}
    <div class="col-md-8 post">
        <h2>{% blocktrans with m=month|date:_('N, Y') %}Monthly archive {{ m }}{% endblocktrans %}</h2>

        <ul>
            {% for daily in date_list %}
                <li style="display: inline;">
                    <a href="{% url 'blog:post-day-archive' daily|date:'Y' daily|date:'m' daily|date:'d' %}">{{ daily|date:_('j') }}</a>
                </li>
            {% endfor %}
        </ul>
        <hr/>

        <div>
            <ul>
                {% for post in posts %}
                    <li>{{ post.date_published|date:'Y-m-d' }}&nbsp;&nbsp;&nbsp;
                        <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <hr/>
        {% include 'blog/_pagination.html' with page_obj=page_obj page_range=page_range %}
    </div>
{% endblock %}

templates/blog/post_category_list.html
{% extends "blog/blog_base.html" %}

{% load i18n %}
{% load blog_filters %}

{% block title %}{% trans 'Blog' %} {% trans 'Category' %} : {{ site_title }}{% endblock %}

{% block entry %}
    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <!-- Blog Entry -->
        {% for post in posts %}
            <div class="row">
                <div class="col-md-12">
                    <h3><strong><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></strong></h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ post.get_absolute_url }}?page={{ page_obj.number }}" class="thumbnail">
                        {% if post.thumbnail %}
                            {% load thumbnail %}
                            {% thumbnail post.thumbnail 220x153 crop="smart" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% else %}
                            <img src="http://placehold.it/220x153/aaaaaa/ffffff?text=No+Image" alt="thumbnail">
                        {% endif %}
                    </a>
                </div>
                <div class="col-md-8 post">
                    <p>
                        {{ post.description|truncatewords:30|linebreaks|safe }}
                    </p>
                    <p>
                        <a class="btn btn-sm btn-default" href="{{ post.get_absolute_url }}?page={{ page_obj.number }}">
                            <i class="fa fa-chevron-circle-right fa-fw" aria-hidden="true"></i>&nbsp;
                            {% trans 'Read more' %}
                        </a>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p>
                        {% if post.category.title %}
                            <i class="fa fa-folder"></i>
                            <a href="{% url 'blog:post-category' post.category.slug %}">{{ post.category.title }}</a> |
                        {% endif %}
                        <i class="fa fa-user"></i> <a href="#">{{ post.author }}</a>
                        | <i class="fa fa-calendar"></i> {{ post.date_published|date:"Y-m-d H:m" }}
                        | <i class="fa fa-comment"></i> <a href="#">3 Comments</a>
                        | <i class="fa fa-eye"></i> {{ post.view_count }}
                        | <i class="fa fa-map-marker"></i> {{ post.ip_address|mask_ip_address }}
                    </p>
                </div>
            </div>

            <!-- tags -->
            {% load blog_tags %}
            {% split_tags post.tag as tags %}
            <div class="panel-footer">
                {% for tag in tags %}
                    <a href="{% url 'blog:tagging-post-list' tag %}">
                        <span class="label label-default">{{ tag }}</span>
                    </a>
                {% empty %}
                    <span><i class="fa fa-tags fa-fw" aria-hidden="true"></i>&nbsp; {% trans 'No tag' %}</span>
                {% endfor %}
            </div>
            <hr/>
        {% endfor %}
        {% include 'blog/_pagination.html' with page_obj=page_obj page_range=page_range %}
    </div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/blog_base.html' %}

{% load i18n %}
{% load static %}
{% load blog_filters %}
{% load blog_tags %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ post.title }} : {{ site_title }}{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static "css/codehilite.css" %}">
{% endblock %}

{% block entry %}
    {% get_comment_count for post as comment_count %}

    <!-- Blog Entries Column -->
    <div class="col-md-8">

        <!-- Blog Entry -->
        <div class="row">
            <div class="col-md-12">
                <h3><strong><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></strong></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p>
                    {% if post.category.title %}
                        <i class="fa fa-folder"></i>
                        <a href="{% url 'blog:post-category' post.category.slug %}">{{ post.category.title }}</a> |
                    {% endif %}
                    <i class="fa fa-user"></i> <a href="#">{{ post.author }}</a>
                    | <i class="fa fa-calendar"></i> {{ post.date_published|date:"Y-m-d H:m" }}
                    | <i class="fa fa-comment"></i> <a href="#comment">{{ comment_count }} Comments</a>
                    | <i class="fa fa-eye"></i> {{ post.view_count }}
                    | <i class="fa fa-map-marker"></i> {{ post.ip_address|mask_ip_address }}
                    {% if user.is_superuser %}
                        | <i class="fa fa-edit"></i>
                        <a href="{% url 'admin:blog_post_change' post.id %}">{% trans 'Edit' %}</a>
                    {% endif %}
                </p>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-12 post">
                {% load blog_filters %}
                {{ post.content|markdownify }}
            </div>
        </div>
        <hr/>

        {% load blog_tags %}
        {% get_recent_posts 3 as posts %}

        <!-- Related Posts -->
        <div class="row">
            <div class="col-lg-12">
                <h4>{% trans 'Related Posts' %}</h4>
            </div>
        </div>
        <div class="row">
            {% for p in posts %}
                <div class="col-md-4 col-sm-6">
                    <div class="thumbnail">
                        <a href="{{ p.get_absolute_url }}?page={{ page_obj.number }}">
                            {% if p.thumbnail %}
                                {% load thumbnail %}
                                {% thumbnail p.thumbnail 220x153 crop="smart" as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% else %}
                                <img src="http://placehold.it/220x153/aaaaaa/ffffff?text=No+Image" alt="thumbnail">
                            {% endif %}
                        </a>
                        <div class="caption">
                            <strong>
                                <a href="{{ p.get_absolute_url }}?page={{ page_obj.number }}">{{ p.title|truncatechars:18 }}</a>
                            </strong>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- tags -->
        {% split_tags post.tag as tags %}
        <div class="panel-footer">
            {% for tag in tags %}
                <a href="{% url 'blog:tagging-post-list' tag %}">
                    <span class="label label-default">{{ tag }}</span>
                </a>
            {% empty %}
                <span>&nbsp;</span>
            {% endfor %}
        </div>
        <hr/>

        <!-- Blog Comments -->
        <!--- Disqus Comments tag
        load disqus_tags
        disqus_show_comments
        -->

        <!-- Comments Form -->
        {% if post.allow_comments %}
            <div class="well">
                <h4>{% trans 'Leave a Comment:' %}</h4>
                {% render_comment_form for post %}
            </div>
            <hr/>
        {% else %}
            <div class="alert alert-info">
                <strong>{% trans 'Comments are not allowed.' %}</strong>
            </div>
        {% endif %}

        <!-- Posted Comments -->
        {% if comment_count %}
            <ul class="media-list" id="comment">
                {% render_xtdcomment_tree for post %}
            </ul>
        {% endif %}

        <!-- Pager -->
        <ul class="pager">
            {% with post.get_previous_post as previous_post %}
                {% if previous_post %}
                    <li class="next"><a href="{{ previous_post }}">{% trans 'Older &rarr;' %}</a></li>
                {% else %}
                    <li class="next disabled"><a href="#">{% trans 'Older &rarr;' %}</a></li>
                {% endif %}
            {% endwith %}

            {% with post.get_next_post as next_post %}
                {% if next_post %}
                    <li class="previous">
                        <a href="{{ post.get_next_post }}">{% trans '&larr; Newer' %}</a>
                    </li>
                {% else %}
                    <li class="previous disabled">
                        <a href="#">{% trans '&larr; Newer' %}</a>
                    </li>
                {% endif %}
            {% endwith %}
        </ul>
    </div>
{% endblock %}

templates/blog/tagging_cloud.html
{% extends "blog/blog_base.html" %}

{% load i18n %}

{% block title %}{% trans 'Tag Cloud' %} : {{ site_title }}{% endblock %}

{% block entry %}
    <!-- Tags Column -->
    <div class="col-md-8">
        {% load tagging_tags %}
        {% tag_cloud_for_model blog.Post as tags with steps=6 min_count=1 distribution=log %}
        {% for tag in tags %}
            <a href="{% url 'blog:tagging-post-list' tag.name %}" class="btn btn-default">
                {{ tag.name }} <span class="badge">{{ tag.font_size }}</span>
            </a>
        {% endfor %}
    </div>
{% endblock %}