blog/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (
    PostListView, PostDetailView, PostCategoryView, PostArchiveIndexView, PostYearArchiveView, PostMonthArchiveView,
    PostDayArchiveView,
    TaggingCloudView, TaggingPostListView, LatestPostFeed
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url='/blog/posts'), name='blog-index'),

    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),
    url(r'^posts/$',
        PostListView.as_view(), name='post-list'),

    url(r'^category/(?P<slug>[-\w]+)/$',
        PostCategoryView.as_view(), name='post-category'),

    url(r'^archive/$',
        PostArchiveIndexView.as_view(), name='post-archive'),
    url(r'^archive/(?P<year>\d{4})/$',
        PostYearArchiveView.as_view(), name='post-year-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        PostMonthArchiveView.as_view(month_format='%m'), name='post-month-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        PostDayArchiveView.as_view(month_format='%m'), name='post-day-archive'),

    url(r'^tags/$',
        TaggingCloudView.as_view(), name='tagging-cloud'),
    url(r'^tags/(?P<tag>[^/]+(?u))/$',
        TaggingPostListView.as_view(), name='tagging-post-list'),

    url(r'^feed/$',
        LatestPostFeed(), name='post-feed'),
]

board/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url='/page/board'), name='board-index'),

    url(r'^(?P<slug>[-\w]+)/$',
        MessageListView.as_view(), name='message-list'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        MessageDetailView.as_view(), name='message-detail'),
    url(r'^(?P<slug>[-\w]+)/new/$',
        MessageCreateView.as_view(), name='message-new'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/edit/$',
        MessageUpdateView.as_view(), name='message-edit'),
    url(r'^(?P<slug>[-\w]+)/(?P<pk>\d+)/delete/$',
        MessageDeleteView.as_view(), name='message-delete'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from account.views import UserLoginView

urlpatterns = [
    # Index page
    url(r'^$',
        RedirectView.as_view(url='/page/index'), name='index'),

    # Project own apps
    url(r'^blog/',
        include('blog.urls', namespace='blog')),
    url(r'^board/',
        include('board.urls', namespace='board')),
    url(r'^page/',
        include('page.urls', namespace='page')),
    url(r'^accounts/',
        include('account.urls', namespace='account')),

    url(r'^comments/',
        include('django_comments_xtd.urls')),

    # Admin site
    # Redirect default admin login page into custom login page
    url(r'admin/login/',
        UserLoginView.as_view()),
    url(r'^admin/',
        admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/forms.py
import json
import logging
import urllib

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .models import Message


class MessageForm(forms.ModelForm):
    logger = logging.getLogger(__name__)

    title = forms.CharField(
        label=_('Title'),
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Title'),
                'required': 'True',
            }
        )
    )
    content = forms.CharField(
        label=_('Content'),
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 15,
                'placeholder': _('Content'),
                'required': 'True',
            }
        )
    )
    is_secret = forms.BooleanField(
        label=_('Secret'),
        required=False,
        initial=False,
    )

    class Meta:
        model = Message
        fields = ['title', 'content', 'is_secret']

    def __init__(self, *args, **kwargs):
        self.logger.debug('MessageForm.__init__()')
        # important to "pop" added kwarg before call to parent's constructor
        self.request = kwargs.pop('request')
        super(MessageForm, self).__init__(*args, **kwargs)


class AnonymousMessageForm(MessageForm):
    logger = logging.getLogger(__name__)

    nickname = forms.CharField(
        label=_('Nickname'),
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Nickname'),
                'required': 'True',
            }
        )
    )
    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'required': 'True',
            }
        )
    )

    class Meta:
        model = Message
        fields = ['title', 'content', 'nickname', 'password', 'is_secret']

    def clean(self):
        self.logger.debug('AnonymousMessageForm.clean()')
        # Google reCAPTCHA
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if not result['success']:
            raise forms.ValidationError(_('reCAPTCHA error occurred.'))

        return super(AnonymousMessageForm, self).clean()


class SecretMessageForm(forms.Form):
    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'required': 'True',
            }
        )
    )


class MessageSearchForm(forms.Form):
    TITLE = 'title'
    CONTENT = 'content'
    TITLE_CONTENT = 'title_content'
    NICKNAME = 'nickname'

    where = forms.ChoiceField(
        label=_('Search Fields'),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'required': True,
            }
        ),
        choices=([
            (TITLE, _('Title')),
            (CONTENT, _('Content')),
            (TITLE_CONTENT, _('Title+Content')),
            (NICKNAME, _('Nickname')),
        ]),
        initial=TITLE_CONTENT,
        required=True,
    )
    q = forms.CharField(
        label=_('Search Word'),
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Search Word'),
                'required': 'True',
            }
        )
    )

board/views.py
import logging

from django.conf import settings
from django.contrib.auth.hashers import (
    make_password, check_password
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.views.generic import (
    ListView, DetailView
)
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView, FormMixin
)
from ipware.ip import get_ip

from .forms import (
    MessageForm, AnonymousMessageForm, SecretMessageForm, MessageSearchForm
)
from .models import (
    Message
)
from .viewmixins import (
    PageableMixin, BoardContextMixin
)


class MessageListView(BoardContextMixin, PageableMixin, ListView):
    logger = logging.getLogger(__name__)
    context_object_name = 'messages'
    template_name = 'board/message_list.html'
    form_class = MessageSearchForm

    def __init__(self):
        self.logger.debug('MessageListView.__init__()')
        super(MessageListView, self).__init__()
        self.block_size = 10  # default value

    def get_queryset(self):
        self.logger.debug('MessageListView.get_queryset()')
        form = self.form_class(self.request.GET)
        queryset = Message.objects.published() \
            .select_related('author') \
            .select_related('board') \
            .board(self.kwargs['slug'])

        if form.is_valid():
            where = form.cleaned_data['where']
            q = form.cleaned_data['q']

            queryset = queryset.public()  # search only in public messages

            if where == form.TITLE:
                queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))
            elif where == form.CONTENT:
                queryset = queryset.filter(Q(content__icontains=q))
            elif where == form.TITLE_CONTENT:
                queryset = queryset.filter(Q(title__icontains=q) | Q(content__icontains=q))
            elif where == form.NICKNAME:
                queryset = queryset.filter(Q(nickname__icontains=q))

        return queryset.order_by('-created')

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageListView.get_context_data()')
        context = super(MessageListView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        context['board'] = self.board  # already fetched by BoardContextMixin.dispatch()
        context['form'] = self.form_class
        return context

    def get_paginate_by(self, queryset):
        self.logger.debug('MessageListView.get_paginate_by()')
        self.block_size = self.board.block_size
        return self.board.chunk_size


class MessageDetailView(BoardContextMixin, FormMixin, DetailView):
    logger = logging.getLogger(__name__)
    context_object_name = 'message'
    form_class = SecretMessageForm
    template_name = 'board/message_detail.html'
    unlocked = False

    def post(self, request, *args, **kwargs):
        self.logger.debug('MessageDetailView.post()')
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_object(self, queryset=None):
        self.logger.debug('MessageDetailView.get_object()')
        o = super(MessageDetailView, self).get_object()
        o.view_count += 1
        o.save()
        return o

    def get_queryset(self):
        self.logger.debug('MessageDetailView.get_queryset()')
        return Message.objects.published() \
            .select_related('author') \
            .select_related('board') \
            .board(self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageDetailView.get_context_data()')
        context = super(MessageDetailView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        context['board'] = self.board  # already fetched by BoardContextMixin.dispatch()
        context['hidden'] = False

        if self.object.is_secret and self.request.user != self.object.author and not self.unlocked:
            context['form'] = self.get_form()
            context['hidden'] = True

        return context

    def form_valid(self, form):
        self.logger.debug('MessageDetailView.form_valid()')

        if check_password(form.cleaned_data['password'], self.object.password):
            self.unlocked = True

            # success_url is not specified because it shows the message by itself.
            return self.render_to_response(self.get_context_data(form=form))

        return super(MessageDetailView, self).form_valid(form)


class MessageCreateView(BoardContextMixin, CreateView):
    logger = logging.getLogger(__name__)
    template_name = 'board/message_form.html'

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageCreateView.get_context_data()')
        context = super(MessageCreateView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        context['board'] = self.board  # already fetched by BoardContextMixin.dispatch()
        context['google_recaptcha_site_key'] = settings.GOOGLE_RECAPTCHA_SITE_KEY
        return context

    def get_form_class(self):
        self.logger.debug('MessageCreateView.get_form_class()')

        if self.request.user.is_authenticated():
            return MessageForm
        else:
            return AnonymousMessageForm

    def get_form_kwargs(self):
        # overrides to pass 'self.request' object
        self.logger.debug('MessageCreateView.get_form_kwargs()')
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_initial(self):
        self.logger.debug('MessageCreateView.get_initial()')
        initial = super(MessageCreateView, self).get_initial()
        initial['board'] = self.board
        return initial

    def form_valid(self, form):
        self.logger.debug('MessageCreateView.form_valid()')

        form.instance.board = self.board
        form.instance.ip_address = get_ip(self.request)

        if self.request.user.is_authenticated():
            form.instance.author = self.request.user
            form.instance.nickname = self.request.user.nickname
        else:
            form.instance.author = None
            form.instance.password = form.cleaned_data['password'] = make_password(form.cleaned_data['password'])

        # The following fields are filled by default:
        # created, updated, status, view_count
        return super(MessageCreateView, self).form_valid(form)

    def get_success_url(self):
        self.logger.debug('MessageCreateView.get_success_url()')
        return reverse('board:message-detail', args=(self.object.board.slug, self.object.id,))


class MessageChangeListView(LoginRequiredMixin, PageableMixin, ListView):
    logger = logging.getLogger(__name__)
    context_object_name = 'messages'
    template_name = 'board/message_change_list.html'
    paginate_by = 20
    block_size = 10

    def get_queryset(self):
        self.logger.debug('MessageChangeListView.get_queryset()')
        return Message.objects \
            .select_related('author') \
            .select_related('board') \
            .author(self.request.user) \
            .order_by('-created')

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageChangeListView.get_context_data()')
        context = super(MessageChangeListView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        return context


class MessageUpdateView(BoardContextMixin, UpdateView):
    logger = logging.getLogger(__name__)
    model = Message
    template_name = 'board/message_form.html'

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageUpdateView.get_context_data()')
        context = super(MessageUpdateView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        context['board'] = self.board  # already fetched by BoardContextMixin.dispatch()
        return context

    def get_form_class(self):
        self.logger.debug('MessageUpdateView.get_form_class()')

        if self.request.user.is_authenticated():
            return MessageForm
        else:
            return AnonymousMessageForm

    def get_form_kwargs(self):
        # overrides to pass 'self.request' object
        self.logger.debug('MessageUpdateView.get_form_kwargs()')
        kwargs = super(MessageUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        self.logger.debug('MessageUpdateView.get_success_url()')
        return reverse('board:message-detail', args=(self.object.board.slug, self.object.id,))


class MessageDeleteView(BoardContextMixin, DeleteView):
    logger = logging.getLogger(__name__)
    model = Message
    context_object_name = 'message'
    template_name = 'board/message_confirm_delete.html'

    def get_context_data(self, **kwargs):
        self.logger.debug('MessageDeleteView.get_context_data()')
        context = super(MessageDeleteView, self).get_context_data(**kwargs)
        context['site_title'] = settings.SITE_TITLE
        context['board'] = self.board  # already fetched by BoardContextMixin.dispatch()
        return context

    def get_success_url(self):
        self.logger.debug('MessageDeleteView.get_success_url()')
        return reverse('board:message-list', args=(self.object.board.slug,))

templates/board/_pagination.html
<div class="row">
    <div class="col-md-12 text-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}

                {% for i in page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

templates/board/board_base.html
{% extends "base.html" %}

{% load i18n %}
{% load cache %}
{% load comments_xtd %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <!-- breadcrumb -->
            {% load navbar_tags %}
            {% navbar_breadcrumbs %}

            {% block entry %}{% endblock %}

            {% cache 0 board_sidebar %}
                <!-- Blog Sidebar Widgets Column -->
                <div class="col-md-4">

                    <!-- Side Widget Well -->
                    <div class="well">
                        <h4>Side Widget Well</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci
                            accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                    </div>

                    <!-- Recent Posts Well -->
                    <div class="well">
                        <h4>{% trans 'Recent Posts' %}</h4>
                        {% load board_tags %}
                        <ul>
                            {% get_recent_messages 10 as messages %}
                            {% for message in messages %}
                                <li>
                                    <a href="{% url 'board:message-detail' message.board.slug message.pk %}">{{ message.title|truncatechars:25 }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>

                    <!-- Recent Comments Well -->
                    <div class="well">
                        <h4>{% trans 'Recent Comments' %}</h4>
                        <ul class="media-list">
                            {% render_last_xtdcomments 5 for board.message %}
                        </ul>
                        <!-- Disqus Comments tag
                        load disqus_tags
                        disqus_recent_comments
                        -->
                    </div>
                </div>
            {% endcache %}
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}

templates/board/message_confirm_delete.html
{% extends "board/board_base.html" %}

{% load i18n %}

{% block title %}{{ site_title }} : {{ board.title }}{% endblock %}

{% block entry %}
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ message.title }}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p></p>
                <p>
                    <i class="fa fa-user"></i> <a href="#">{{ message.author }}</a>
                    | <i class="fa fa-calendar"></i> {{ message.created|date:"Y-m-d H:m" }}
                    | <i class="fa fa-comment"></i> <a href="#">3 Comments</a>
                    | <i class="fa fa-eye"></i> <a href="#">{{ message.view_count }}</a>
                    {% if user.is_superuser %}
                        | <i class="fa fa-edit"></i>
                        <a href="{% url 'board:message-edit' message.board.slug message.id %}">{% trans 'Edit' %}</a>
                    {% endif %}
                </p>
            </div>
        </div>
        <hr/>
        <div class="alert alert-danger">
            <form class="form-inline" action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    {% trans 'Are you sure to delete?' %}
                </div>
                <button class="btn btn-danger" type="submit">
                    <span class="fa fa-trash fa-fw" aria-hidden="true"></span> {% trans 'Delete' %}
                </button>
            </form>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-12 post">
                {{ message.content|linebreaks|safe }}
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-md-6">
                <a href="{% url 'board:message-list' board.slug %}?page={{ request.GET.page }}" class="btn btn-default">
                    <i class="fa fa-list-ul fa-fw" aria-hidden="true"></i>&nbsp;
                    {% trans 'List' %}
                </a>
            </div>
            <div class="col-md-6">
                <a href="{% url 'board:message-new' board.slug %}" class="btn btn-info pull-right">
                    <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>&nbsp;
                    {% trans 'Write' %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/board/message_detail.html
{% extends "board/board_base.html" %}

{% load i18n %}
{% load board_filters %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ message.title }} : {{ site_title }}{% endblock %}

{% block entry %}
    {% get_comment_count for message as comment_count %}

    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <h3>{{ message.title }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p></p>
                <p>
                    <i class="fa fa-user"></i> <a href="#">{{ message.nickname }}</a>
                    | <i class="fa fa-calendar"></i> {{ message.created|date:"Y-m-d H:m" }}
                    | <i class="fa fa-comment"></i> <a href="#comment">{{ comment_count }} Comments</a>
                    | <i class="fa fa-eye"></i> {{ message.view_count }}
                    | <i class="fa fa-map-marker"></i> {{ message.ip_address|mask_ip_address }}
                    {% if user.is_superuser %}
                        | <i class="fa fa-edit"></i>
                        <a href="{% url 'board:message-edit' message.board.slug message.id %}?page={{ request.GET.page }}">
                            {% trans 'Edit' %}
                        </a>
                        | <i class="fa fa-trash"></i>
                        <a href="{% url 'board:message-delete' message.board.slug message.id %}?page={{ request.GET.page }}">
                            {% trans 'Delete' %}
                        </a>
                    {% endif %}
                </p>
            </div>
        </div>
        <hr/>
        {% if hidden %}
            {% if message.author %}
                {% trans 'You may see your own message after you sign in.' %}
            {% else %}
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <form action="." method="post" accept-charset="UTF-8" role="form">
                                    {% csrf_token %}
                                    {% if form.errors %}
                                        <div class="alert alert-danger" role="alert">
                                            {% for error in form.errors.values %}
                                                {{ error|striptags }}
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                    <fieldset>
                                        <div class="form-group">
                                            {{ form.password }}
                                            {{ form.password.errors }}
                                        </div>
                                        <input class="btn btn-mg btn-success btn-block" type="submit"
                                               value="{% trans 'View' %}">
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% else %}
            <div class="row">
                <div class="col-md-12 post">
                    {{ message.content|linebreaks|safe }}
                </div>
            </div>
        {% endif %}
        <hr/>

        <!-- Comments Form -->
        {% if board.allow_comments %}
            <div class="well">
                <h4>{% trans 'Leave a Comment:' %}</h4>
                {% render_comment_form for message %}
            </div>
            <hr/>
        {% else %}
            <div class="alert alert-info">
                <strong>{% trans 'Comments are not allowed.' %}</strong>
            </div>
        {% endif %}

        <!-- Posted Comments -->
        {% if comment_count %}
            <ul class="media-list" id="comment">
                {% render_xtdcomment_tree for message %}
            </ul>
            <hr/>
        {% endif %}
        <div class="row">
            <div class="col-md-6">
                <a href="{% url 'board:message-list' board.slug %}?page={{ request.GET.page }}" class="btn btn-default">
                    <i class="fa fa-list-ul fa-fw" aria-hidden="true"></i>&nbsp;
                    {% trans 'List' %}
                </a>
            </div>
            <div class="col-md-6">
                <a href="{% url 'board:message-new' board.slug %}" class="btn btn-info pull-right">
                    <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>&nbsp;
                    {% trans 'Write' %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/board/message_list.html
{% extends "board/board_base.html" %}

{% load i18n %}
{% load board_filters %}

{% block title %}{{ site_title }} : {{ board.title }}{% endblock %}

{% block entry %}
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="text-center col-md-1">{% trans 'No' %}</th>
                        <th class="text-center col-md-8">{% trans 'Title' %}</th>
                        <th class="text-center col-md-2">{% trans 'Author' %}</th>
                        <th class="text-center col-md-1">{% trans 'At' %}</th>
                        <th style="display: none;" class="text-center">{% trans 'View Count' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for message in messages %}
                        <tr>
                            <td class="text-center">{{ message.id }}</td>
                            <td>
                                <a href="{% url 'board:message-detail' message.board.slug message.id %}?page={{ page_obj.number }}">
                                    {{ message.title }}
                                </a>
                                {% if message.is_secret %}
                                    <i class="fa fa-lock"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">{{ message.nickname }}</td>
                            <td class="text-center">
                                {% if message.created|is_today %}
                                    {{ message.created|date:"H:m" }}
                                {% else %}
                                    {{ message.created|date:"Y.m.d" }}
                                {% endif %}
                            </td>
                            <td style="display: none;" class="text-center">{{ message.view_count }}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="6" class="text-center">
                                <strong>{% trans 'There is no message yet.' %}</strong>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <hr/>

        <!-- Buttons -->
        <div class="row">
            <div class="col-md-12">
                <a href="{% url 'board:message-new' board.slug %}" class="btn btn-info pull-right">
                    <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>&nbsp;
                    {% trans 'Write' %}
                </a>
            </div>
        </div>

        {% include 'board/_pagination.html' with page_obj=page_obj page_range=page_range %}

        <div class="row">
            <div class="col-md-12 text-center">
                <form class="form-inline">
                    {{ form.where }}
                    <div class="form-group">{{ form.q }}</div>
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-search fa-fw" aria-hidden="true"></i>&nbsp;
                        {% trans 'Search' %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}