blog/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .views import (
    PostListView, PostDetailView, PostCategoryView, PostArchiveIndexView, PostYearArchiveView, PostMonthArchiveView,
    PostDayArchiveView,
    TaggingCloudView, TaggingPostListView, LatestPostFeed
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url='/blog/posts'), name='blog-index'),

    url(r'^(?P<pk>\d+)/(?P<slug>[-\w]+)/$',
        PostDetailView.as_view(), name='post-detail'),
    url(r'^posts/$',
        PostListView.as_view(), name='post-list'),

    url(r'^category/(?P<slug>[-\w]+)/$',
        PostCategoryView.as_view(), name='post-category'),

    url(r'^archive/$',
        PostArchiveIndexView.as_view(), name='post-archive'),
    url(r'^archive/(?P<year>\d{4})/$',
        PostYearArchiveView.as_view(), name='post-year-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/$',
        PostMonthArchiveView.as_view(month_format='%m'), name='post-month-archive'),
    url(r'^archive/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        PostDayArchiveView.as_view(month_format='%m'), name='post-day-archive'),

    url(r'^tags/$',
        TaggingCloudView.as_view(), name='tagging-cloud'),
    url(r'^tags/(?P<tag>[^/]+(?u))/$',
        TaggingPostListView.as_view(), name='tagging-post-list'),

    url(r'^feed/$',
        LatestPostFeed(), name='post-feed'),
]

account/forms.py
import json
import logging
import urllib

from django import forms
from django.conf import settings
from django.contrib.auth.forms import (
    ReadOnlyPasswordHashField, AuthenticationForm
)
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _

from .models import (
    User, UserManager
)


class UserLoginForm(AuthenticationForm):
    logger = logging.getLogger(__name__)

    username = forms.EmailField(
        label=_('Email'),
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Email address'),
                'required': 'True',
            }
        )
    )
    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'required': 'True',
            }
        )
    )

    def clean(self):
        self.logger.debug('UserLoginForm.clean()')
        # Google reCAPTCHA
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if not result['success']:
            raise forms.ValidationError(_('reCAPTCHA error occurred.'))

        return super(UserLoginForm, self).clean()


class UserCreationForm(forms.ModelForm):
    logger = logging.getLogger(__name__)

    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    email = forms.EmailField(
        label=_('Email'),
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Email address'),
                'required': 'True',
            }
        )
    )
    last_name = forms.CharField(
        label=_('Last name'),
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Last name'),
                'required': 'True',
            }
        )
    )
    first_name = forms.CharField(
        label=_('First name'),
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('First name'),
                'required': 'True',
            }
        )
    )
    nickname = forms.CharField(
        label=_('Nickname'),
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Nickname'),
                'required': 'True',
            }
        )
    )
    password1 = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'required': 'True',
            }
        )
    )
    password2 = forms.CharField(
        label=_('Password confirmation'),
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password confirmation'),
                'required': 'True',
            }
        )
    )

    class Meta:
        model = User
        fields = ('email', 'last_name', 'first_name', 'nickname')

    def save(self, commit=True):
        self.logger.debug('UserCreationForm.save()')

        user = super(UserCreationForm, self).save(commit=False)

        user.email = UserManager.normalize_email(self.cleaned_data['email'])
        # Save the provided password in hashed format
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True

        if commit:
            user.save()

        return user

    def clean_password2(self):
        self.logger.debug('UserCreationForm.clean_password2()')

        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords don't match"))

        return password2


class UserChangeForm(forms.ModelForm):
    logger = logging.getLogger(__name__)

    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField(
        label=_('Password')
    )

    class Meta:
        model = User
        fields = ('email', 'password', 'last_name', 'first_name', 'is_active', 'is_superuser')

    def clean_password(self):
        self.logger.debug('UserChangeForm.clean_password()')

        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class WebUserCreationForm(UserCreationForm):
    logger = logging.getLogger(__name__)

    terms = forms.BooleanField(
        label=_('Terms of service'),
        required=True,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'required': 'True',
            }
        ),
        error_messages={
            'required': _('You must agree to the Terms of service to sign up'),
        }
    )
    privacy = forms.BooleanField(
        label=_('Privacy policy'),
        required=True,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'required': 'True',
            }
        ),
        error_messages={
            'required': _('You must agree to the Privacy policy to sign up'),
        }
    )

    def __init__(self, *args, **kwargs):
        self.logger.debug('WebUserCreationForm.__init__()')
        # important to "pop" added kwarg before call to parent's constructor
        self.request = kwargs.pop('request')
        super(UserCreationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.logger.debug('WebUserCreationForm.save()')

        user = super(WebUserCreationForm, self).save(commit=False)

        if commit:
            if settings.EMAIL_ACCOUNT_ACTIVATION:
                user.is_active = False
                user.save()

                # Send user activation mail
                current_site = get_current_site(self.request)
                subject = (_('Welcome To %s! Confirm Your Email') % current_site.name)
                message = render_to_string('registration/user_activate_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': PasswordResetTokenGenerator().make_token(user),
                })
                email = EmailMessage(subject, message, to=[user.email])
                email.send()
            else:
                user.is_active = True
                user.save()

        return user

    def clean(self):
        self.logger.debug('WebUserCreationForm.clean()')
        # Google reCAPTCHA
        ''' Begin reCAPTCHA validation '''
        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req = urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''

        if not result['success']:
            raise forms.ValidationError(_('reCAPTCHA error occurred.'))

        return super(WebUserCreationForm, self).clean()

templates/comments/form.html
{% load i18n %}
{% load comments %}

<form method="POST" action="{% comment_form_target %}" class="form-horizontal">
    {% csrf_token %}
    <fieldset>
        <input type="hidden" name="next" value="{% url 'comments-xtd-sent' %}"/>

        <div class="alert alert-danger hidden" data-comment-element="errors">
        </div>

        {% for field in form %}
            {% if field.is_hidden %}
                <div>{{ field }}</div>{% endif %}
        {% endfor %}

        <div style="display:none">{{ form.honeypot }}</div>

        <div class="form-group {% if 'comment' in form.errors %}has-error{% endif %}">
            <div class="col-lg-offset-1 col-md-offset-1 col-lg-10 col-md-10">
                {{ form.comment }}
            </div>
        </div>

        {% if not request.user.is_authenticated %}
            <div class="form-group {% if 'name' in form.errors %}has-error{% endif %}">
                <label for="id_name" class="control-label col-lg-3 col-md-3">
                    {{ form.name.label }}
                </label>
                <div class="col-lg-7 col-md-7">
                    {{ form.name }}
                </div>
            </div>

            <div class="form-group {% if 'email' in form.errors %}has-error{% endif %}">
                <label for="id_email" class="control-label col-lg-3 col-md-3">
                    {{ form.email.label }}
                </label>
                <div class="col-lg-7 col-md-7">
                    {{ form.email }}
                    <span class="help-block">{{ form.email.help_text }}</span>
                </div>
            </div>

            <div class="form-group {% if 'url' in form.errors %}has-error{% endif %}">
                <label for="id_url" class="control-label col-lg-3 col-md-3">
                    {{ form.url.label }}
                </label>
                <div class="col-lg-7 col-md-7">
                    {{ form.url }}
                </div>
            </div>
        {% endif %}

        <div class="form-group">
            <div class="col-lg-offset-3 col-md-offset-3 col-lg-7 col-md-7">
                <div class="checkbox">
                    <label for="id_followup{% if cid %}_{{ cid }}{% endif %}">
                        {{ form.followup }}&nbsp;&nbsp;{{ form.followup.label }}
                    </label>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="form-group">
        <div class="col-lg-offset-3 col-md-offset-3 col-lg-7 col-md-7">
            <input type="submit" name="post" value="{% trans 'Write' %}" class="btn btn-primary"/>
            <input type="submit" name="preview" value="{% trans 'Preview' %}" class="btn btn-default"/>
        </div>
    </div>
</form>

templates/comments/list.html
{% load i18n %}
{% load comments %}
{% load comments_xtd %}

<ul class="media-list">
    {% for comment in comment_list %}
        <li id="comments" class="media">
            <div class="media-left">
                <a name="c{{ comment.id }}">{{ comment.user_email|xtd_comment_gravatar }}</a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">
                    {% if comment.url and not comment.is_removed %}
                        <a href="{{ comment.url }}" target="_new">
                    {% endif %}
                    {{ comment.name }}
                    {% if comment.url %}
                        </a>
                    {% endif %}
                    <small>{{ comment.submit_date }}</small>
                    &nbsp;&nbsp;
                    <a class="permalink" title="comment permalink" href="{% get_comment_permalink comment %}">¶</a>
                </h4>
                {% if comment.is_removed %}
                    <p>{% trans "This comment has been removed." %}</p>
                {% else %}
                    {% include "includes/django_comments_xtd/comment_content.html" with content=comment.comment %}
                    <p>
                        {% if comment.allow_thread and not comment.is_removed %}
                            <a class="small mutedlink" href="{{ comment.get_reply_url }}">{% trans "Reply" %}</a>
                        {% endif %}
                    </p>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>